[phases.setup]
nixPkgs = ['python39', 'chromium', 'chromedriver']

[variables]
CHROME_BIN = '/usr/bin/chromium'
CHROMEDRIVER_PATH = '/usr/bin/chromedriver'
PYTHONUNBUFFERED = "1"

[start]
cmd = "gunicorn app:app" 